export const queryKeys = {
  dashboard: ["dashboard"] as const,
  decisions: (projectId: string, revision: number) => ["project", projectId, revision, "decisions"] as const,
  handoff: (projectId: string, revision: number) => ["project", projectId, revision, "handoff"] as const,
  health: (projectId: string, revision: number) => ["project", projectId, revision, "health"] as const,
  plan: (projectId: string, revision: number) => ["project", projectId, revision, "execution-plan"] as const,
  savedView: (projectId: string, revision: number, view: string) => ["project", projectId, revision, "view", view] as const,
  explain: (workItemId: string, version: number) => ["work-item", workItemId, version, "explanation"] as const,
  github: ["account", "github"] as const,
  githubRepos: ["account", "github", "repositories"] as const,
  accountConfig: ["account", "config"] as const,
  mcpTokens: ["account", "mcp-tokens"] as const,
  oauthConnections: ["account", "oauth-connections"] as const,
  integrations: (projectId: string) => ["project", projectId, "integrations"] as const,
  integrationResources: (provider: string, connectionId: string) => ["integration", provider, connectionId, "resources"] as const,
  integrationProjects: (provider: string, connectionId: string, accountId: string) => ["integration", provider, connectionId, "account", accountId, "projects"] as const,
  integrationChannels: (provider: string, connectionId: string) => ["integration", provider, connectionId, "channels"] as const,
  integrationCandidates: (bindingId: string) => ["integration", "binding", bindingId, "candidates"] as const,
};
