/**
 * E6 — Tier A, the request-raising half (RECONCILIATION_ARCHITECTURE.md §9). No database
 * connection of its own: `judgmentRequestStatement` is a plain statement builder in the
 * same shape as `resolve.ts`'s `aliasStatement`, called from `lib/store.ts` inside the
 * same batch that creates the proposal — a judgment request that fails to commit must not
 * outlive the item it's about. Kept out of `lib/planning/judgments.ts` (the answering
 * half, which needs `organizationFor`/`executeCommand` from `lib/store.ts`) specifically
 * so `lib/store.ts` can import this file without a circular import — the identical reason
 * `lib/planning/decisions.ts`'s `raiseConflictDecisions` isn't called from inside
 * `lib/store.ts` itself.
 */
import type { PgD1, PgD1PreparedStatement } from "@/db/pg-d1";

export function judgmentId() {
  return `jdg_${crypto.randomUUID().replaceAll("-", "")}`;
}

export type JudgmentEvidence = { sharedArtifacts: string[]; reason: string };

/**
 * §9's exact example: name the candidate, not just "a possible match." An agent deciding
 * whether to answer has to know *which* existing item it's being asked about, since the
 * proposal itself may resemble several.
 */
export function buildJudgmentQuestion(proposalTitle: string, candidate: { itemKey: string; title: string }): string {
  return `Is "${proposalTitle}" the same work as ${candidate.itemKey} "${candidate.title}"?`;
}

/**
 * §9's honesty check, heuristic by necessity: "'They're different' is rejected;
 * 'different — #31 rotates the signing key, this renews the client's token' is stored as
 * a label." There is no way to server-side-verify a justification actually names a real
 * artifact or behavior without the same repository access the agent has — this can only
 * reject the laziest non-answers (too short, or a known stock phrase), not confirm the
 * content is true or even relevant. That is the honest limit of this check, not a gap to
 * paper over with a false sense of verification.
 */
const TRIVIAL_JUSTIFICATIONS = new Set([
  "different", "same", "yes", "no", "duplicate", "not a duplicate", "not the same",
  "they are different", "they're different", "they are the same", "they're the same",
  "it is different", "it's different", "unrelated", "not related",
]);
const MIN_JUSTIFICATION_LENGTH = 15;

export function isAcceptableJustification(justification: string): boolean {
  const trimmed = justification.trim().toLowerCase().replace(/[.!?]+$/, "");
  if (trimmed.length < MIN_JUSTIFICATION_LENGTH) return false;
  if (TRIVIAL_JUSTIFICATIONS.has(trimmed)) return false;
  return true;
}

export type JudgmentRequestInput = {
  id: string;
  organizationId: string;
  projectId: string;
  leftItemId: string;
  rightItemId: string;
  question: string;
  evidence: JudgmentEvidence;
  sourceId?: string;
};

/**
 * `id` is generated by the caller (`judgmentId()`), not here — unlike `aliasStatement`'s
 * own internally-generated id, this one has to flow back to the agent as `pairId` in the
 * tool result, since answering it is a *separate*, later tool call
 * (`submit_reconciliation_judgment`) that needs something to reference.
 *
 * `ON CONFLICT DO NOTHING`: the same new-item/candidate pair should ask its question
 * once, not once per batch retry or per identical proposal repeated across sessions —
 * `UNIQUE(project_id, left_item_id, right_item_id)` (db/setup.ts) is what makes a second
 * attempt at the same question a silent no-op instead of a duplicate row an agent would
 * see twice in `needsJudgment`.
 */
export function judgmentRequestStatement(db: PgD1, input: JudgmentRequestInput): PgD1PreparedStatement {
  return db.prepare(
    "INSERT INTO reconciliation_judgment_requests (id, organization_id, project_id, left_item_id, right_item_id, question, evidence, requested_by_source_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (project_id, left_item_id, right_item_id) DO NOTHING",
  ).bind(
    input.id, input.organizationId, input.projectId, input.leftItemId, input.rightItemId,
    input.question.slice(0, 500), JSON.stringify(input.evidence), input.sourceId ?? null,
  );
}

export type EscalationRateReport = { itemsCreated: number; judgmentRequests: number; rate: number };

/**
 * §13's own gate for this milestone: "escalation rate < 5% of proposals." "Proposals
 * received" isn't a number this product logs anywhere on its own — a proposal either
 * collapses into an existing item (and is never counted as "created" at all), becomes a
 * plain create, or becomes a create *plus* a judgment request. Non-archived items created
 * is the honest, actually-countable proxy: every judgment request corresponds to exactly
 * one created item, so this ratio is the fraction of *created* work that also raised a
 * question, a fair reading of the gate's own intent even if not literally "of proposals."
 * A plain count query, not `organizationFor`-gated — this module still doesn't import
 * `lib/store.ts` (see the module comment), since the caller already has `organizationId`
 * resolved.
 */
export async function measureEscalationRate(db: PgD1, organizationId: string, projectId: string): Promise<EscalationRateReport> {
  const [itemsRow, judgmentsRow] = await Promise.all([
    db.prepare("SELECT COUNT(*)::int AS count FROM work_items WHERE project_id = ? AND organization_id = ? AND archived_at IS NULL").bind(projectId, organizationId).first<{ count: number }>(),
    db.prepare("SELECT COUNT(*)::int AS count FROM reconciliation_judgment_requests WHERE project_id = ? AND organization_id = ?").bind(projectId, organizationId).first<{ count: number }>(),
  ]);
  const itemsCreated = Number(itemsRow?.count ?? 0);
  const judgmentRequests = Number(judgmentsRow?.count ?? 0);
  return { itemsCreated, judgmentRequests, rate: itemsCreated === 0 ? 0 : judgmentRequests / itemsCreated };
}
