import { ANNOTATION_EDGE_TYPES, DAG_EDGE_TYPES } from "@/lib/graph/edges.ts";
import { SAVED_VIEWS } from "@/lib/planning/views.ts";

export function transitionSchema() {
  return { type: "object", required: ["project_id", "work_item_id", "expected_version", "idempotency_key"], properties: { project_id: { type: "string" }, work_item_id: { type: "string" }, expected_version: { type: "number" }, source_id: { type: "string" }, reason: { type: "string" }, idempotency_key: { type: "string" } } };
}

export function interactionSchema(event: string) {
  return { type: "object", required: ["project_id", "source_id", "external_interaction_id"], properties: { project_id: { type: "string" }, source_id: { type: "string" }, external_interaction_id: { type: "string" }, sequence: { type: "number" }, outcome: { type: "string" }, summary: { type: "string" }, event: { const: event } } };
}

/**
 * Raw JSON Schema, hand-written per tool, not derived from a validator library: the
 * low-level Server's tools/list handler returns exactly this array unvalidated (per
 * @modelcontextprotocol/server's docs: "A client's tools/list returns exactly the array
 * you wrote, the SDK derived none of it"). Its own type wants string-literal `type`
 * fields and mutable arrays throughout a deeply heterogeneous structure; encoding that
 * precisely across ~30 differently-shaped schemas buys nothing a human reading this file
 * doesn't already get from the object literals themselves, so callers cast through
 * unknown at the one place it meets the SDK's stricter type instead.
 */
export type ToolDef = { name: string; description: string; inputSchema: Record<string, unknown> };

export const tools = [
  { name: "resolve_project", description: "Resolve the canonical Planbraid project for the work at hand. Always call this first, passing this session's absolute working directory and the repository's git remote when you have them: those identify a project exactly, while a name alone can miss and lead to a duplicate.", inputSchema: { type: "object", properties: { project_id: { type: "string" }, query: { type: "string" }, directory: { type: "string", description: "Absolute path of the current working directory." }, git_remote: { type: "string", description: "The repository's origin remote, in any form; git@ and .git spellings are normalized." } } } },
  { name: "create_project", description: "Create a Planbraid project for a repository or initiative. Pass directory and git_remote whenever you have them: proposals are matched against existing projects first, so calling this for a repository someone already set up in the web UI returns that project (status 'matched') rather than creating a duplicate. Check the returned status and use the returned project_id either way.", inputSchema: { type: "object", required: ["name", "idempotency_key"], properties: { name: { type: "string" }, directory: { type: "string", description: "Absolute path of the repository or working directory this project tracks, for example /Users/you/Projects/my-app." }, description: { type: "string" }, git_remote: { type: "string", description: "Canonical remote URL, for example https://github.com/owner/repo." }, idempotency_key: { type: "string" } } } },
  { name: "update_project", description: "Update a project's details. Use this to bind your absolute working directory to a project that was created in the web UI without one: a project with no directory cannot be matched to this repository by future sessions. Omitted fields are left unchanged.", inputSchema: { type: "object", required: ["project_id", "idempotency_key"], properties: { project_id: { type: "string" }, name: { type: "string" }, description: { type: "string" }, directory: { type: "string", description: "Absolute path of the working directory this project tracks." }, git_remote: { type: "string" }, idempotency_key: { type: "string" } } } },
  { name: "get_project_brief", description: "Get compact current project context: active, ready, blocked, review, recent events, sources, and recommended next actions.", inputSchema: { type: "object", required: ["project_id"], properties: { project_id: { type: "string" }, focus: { type: "string" } } } },
  { name: "list_work_items", description: "List current project work with structured status/source filters.", inputSchema: { type: "object", required: ["project_id"], properties: { project_id: { type: "string" }, status: { type: "string" }, source_id: { type: "string" }, query: { type: "string" }, limit: { type: "number" } } } },
  { name: "get_ready_work", description: "Get work that is actually actionable right now: unblocked by dependencies, not claimed by another active session, ranked by how much finishing it unlocks. Prefer this over list_work_items when deciding what to work on next.", inputSchema: { type: "object", required: ["project_id"], properties: { project_id: { type: "string" }, source_id: { type: "string", description: "This session's source ID. Excludes work already claimed by other active sessions; does not exclude this session's own claims." }, limit: { type: "number", description: "Defaults to 5." }, avoid_collisions: { type: "boolean", description: "Defaults to true. Set false to see all unblocked work regardless of other sessions' claims." } } } },
  { name: "get_work_item", description: "Get one work item with source, evidence, dependencies, and recent events.", inputSchema: { type: "object", required: ["work_item_id"], properties: { work_item_id: { type: "string" } } } },
  { name: "create_work_items", description: "Propose one or more work items in one operation. Proposals are matched against work the project already has: a restatement of existing work returns that item's ID instead of creating a duplicate, so always use the returned workItemId rather than assuming a new item was created. Check each result's status field (created, matched, or uncertain) and any warning before starting work. When a created item is a subset, superset, or overlap of existing work, or naturally follows it, the result's relation field says so and a real link is recorded automatically; when it directly conflicts with existing work (opposite intent, same concrete file or endpoint), a decision is also raised for a person to resolve: check for a relation field with type CONFLICT and a decision field in the result. When a match is genuinely ambiguous, the result carries needsJudgment (also collected at the top level): answer it with submit_reconciliation_judgment if you can tell from the repository, naming what settles it. Write every item's description with the same care you'd want from a handoff: a person or another agent should be able to pick it up cold with no other context. A vague one-liner is a sign the work was not actually thought through yet.", inputSchema: { type: "object", required: ["project_id", "items", "idempotency_key"], properties: { project_id: { type: "string" }, source_id: { type: "string" }, import_request_id: { type: "string", description: "Set this when reporting your full local plan in response to a pending import request (surfaced by register_agent_session), so Planbraid can mark that request complete. Omit otherwise." }, idempotency_key: { type: "string" }, items: { type: "array", maxItems: 50, items: { type: "object", required: ["title", "description"], properties: { ref: { type: "string", description: "Optional caller-chosen handle echoed back in the result, for correlating proposals with outcomes." }, title: { type: "string" }, description: { type: "string", description: "Required, and never a restatement of the title. Cover what actually changes (files, components, endpoints, or behavior, where already known), the concrete acceptance criteria or definition of done, and any constraint, edge case, or open question already known. Someone reading only this field should understand the work without asking you anything else." }, status: { type: "string" }, priority: { type: "string" }, depends_on: { type: "array", items: { type: "string" }, description: "IDs of prerequisite tasks: this item cannot start until each one is done. Each entry is either another item's ref from this same call, or the work_item_id of a task that already exists." } } } } } } },
  { name: "accept_work_items", description: "Record that the user accepted proposed work, naming who decided. Work you propose is recorded as a proposal, not as an accepted plan; this is how a proposal becomes real work. Only call it when the user actually said so in this conversation; an acceptance you report is stored as their statement, attributed to them.", inputSchema: { type: "object", required: ["project_id", "work_item_ids", "stated_by", "idempotency_key"], properties: { project_id: { type: "string" }, work_item_ids: { type: "array", items: { type: "string" }, maxItems: 100 }, stated_by: { type: "string", description: "Who accepted this, as they identify themselves. Required: an acceptance with nobody behind it is not an acceptance." }, reason: { type: "string" }, source_id: { type: "string" }, idempotency_key: { type: "string" } } } },
  { name: "update_work_item", description: "Update descriptive fields using optimistic expected_version concurrency.", inputSchema: { type: "object", required: ["project_id", "work_item_id", "expected_version", "idempotency_key"], properties: { project_id: { type: "string" }, work_item_id: { type: "string" }, expected_version: { type: "number" }, source_id: { type: "string" }, title: { type: "string" }, description: { type: "string" }, priority: { type: "string" }, assignee: { type: ["string", "null"] }, idempotency_key: { type: "string" } } } },
  { name: "start_work", description: "Atomically claim/start ready work and attribute it to this source session. Takes an exclusive lease: fails with WORK_LEASED (409) naming the current holder if another live session already holds one, unless force is set.", inputSchema: { ...transitionSchema(), properties: { ...transitionSchema().properties, force: { type: "boolean", description: "Override another live session's lease and take it over. The takeover is recorded in the transition's own reason." } } } },
  { name: "block_work", description: "Mark work blocked with a structured reason, optionally naming the specific prerequisite tasks it is waiting on.", inputSchema: { ...transitionSchema(), properties: { ...transitionSchema().properties, blocker_work_item_ids: { type: "array", items: { type: "string" }, description: "IDs of tasks that must complete before this one can proceed. A 'blocks' dependency edge is recorded from each one to this task." } }, required: ["project_id", "work_item_id", "expected_version", "reason", "idempotency_key"] } },
  { name: "link_work_items", description: "Declare a relationship between two work items: an ordering dependency (one blocks or is required by the other) or a non-ordering annotation (related, duplicate, superseded). Name fields for role, not position: the prerequisite is the task that must happen first.", inputSchema: { type: "object", required: ["project_id", "prerequisite_work_item_id", "dependent_work_item_id", "idempotency_key"], properties: { project_id: { type: "string" }, prerequisite_work_item_id: { type: "string", description: "The task that must be resolved first." }, dependent_work_item_id: { type: "string", description: "The task that is waiting on the prerequisite." }, type: { type: "string", enum: [...DAG_EDGE_TYPES, ...ANNOTATION_EDGE_TYPES], description: "Defaults to 'blocks'. Use 'requires' for a soft dependency, or an annotation type ('relates_to', 'duplicates', 'supersedes') for a non-ordering relationship." }, reason: { type: "string" }, source_id: { type: "string" }, idempotency_key: { type: "string" } } } },
  { name: "report_progress", description: "Append a concise, durable progress update without replacing task description.", inputSchema: { type: "object", required: ["project_id", "work_item_id", "summary", "idempotency_key"], properties: { project_id: { type: "string" }, work_item_id: { type: "string" }, source_id: { type: "string" }, summary: { type: "string" }, idempotency_key: { type: "string" } } } },
  { name: "report_completion", description: "Report implementation completion with evidence. This always lands the item in review, not done: reaching done requires either a person's decision or evidence this call attached (or that already existed on the item, for example from a repository observation) actually being machine-verified. There is no way to mark your own claim verified from this call: that flag was removed because nothing checked it.", inputSchema: { type: "object", required: ["project_id", "work_item_id", "expected_version", "summary", "idempotency_key"], properties: { project_id: { type: "string" }, work_item_id: { type: "string" }, expected_version: { type: "number" }, source_id: { type: "string" }, summary: { type: "string" }, evidence: { type: "array", maxItems: 20, items: { type: "object", properties: { type: { type: "string" }, label: { type: "string" }, uri: { type: "string" }, result: { type: "string" } } } }, idempotency_key: { type: "string" } } } },
  { name: "reopen_work", description: "Reopen completed/review work with a reason and current expected version.", inputSchema: { ...transitionSchema(), required: ["project_id", "work_item_id", "expected_version", "reason", "idempotency_key"] } },
  { name: "cancel_work", description: "Cancel or reject a work item: it no longer needs doing, was superseded by something else, turned out to be a duplicate, or was abandoned. Open to either an agent or a person: an agent noticing its own proposal is no longer needed, or that requirements changed, should be able to say so directly, the same way record_decision is open to agents even though resolve_decision is not. Always pass resolution: an 'unspecified' cancellation (the default if you omit it) is invisible to get_planning_context's rejected bucket, so a later proposal of the same idea will not be warned off it. Use 'rejected' when the approach itself was wrong, 'superseded' when something else replaces it, 'duplicate' when it restates other work, 'obsolete' or 'abandoned' otherwise.", inputSchema: { ...transitionSchema(), properties: { ...transitionSchema().properties, resolution: { type: "string", enum: ["rejected", "deferred", "superseded", "duplicate", "abandoned", "obsolete", "unspecified"], description: "Why this is being cancelled. Strongly recommended: see the tool description." } }, required: ["project_id", "work_item_id", "expected_version", "reason", "idempotency_key"] } },
  { name: "register_agent_session", description: "Register or resume any MCP client, agent, or personal-model session and return a stable Planbraid source ID. A new external conversation resumes the most recently ended source for the same project, provider, and authenticated account; an already-active conversation remains a separate source. Always call this first, before proposing or changing anything. If the project already has open work, the response includes existingWork (a count and the most recently touched items) with a note telling you to read the plan before amending it - this is the whole point of the platform: build on what already exists instead of silently re-planning from scratch. Follow up with get_planning_context (for a specific objective) or get_handoff_package (a full cold-start briefing) before create_work_items. The response may also include pendingImportRequest if the user has asked this specific agent, from the website, to report everything it knows about the project - when present, read your full local task list or plan for this project and report it in one create_work_items call with import_request_id set to its id.", inputSchema: { type: "object", required: ["project_id", "provider", "external_session_id"], properties: { project_id: { type: "string" }, provider: { type: "string", description: "Free-form client, agent, or provider name; for example codex, local-llama, or my-personal-agent." }, external_session_id: { type: "string", description: "Stable conversation or session identifier from the connecting client." }, title: { type: "string" }, model: { type: "string", description: "Optional free-form model name or identifier." }, account_label: { type: "string", description: "Optional. Which of the user's logins for this model you are running as, when you know it (for example 'work'). Ignored when the connection already identifies its account, which is the normal case - do not invent a value." }, coding_space_id: { type: "string" }, assurance: { type: "string" } } } },
  { name: "begin_interaction", description: "Record the start of one user-prompt/agent-turn interaction.", inputSchema: interactionSchema("started") },
  { name: "sync_interaction", description: "Close and reconcile an agent interaction after task lifecycle tools have been called. Creates one durable notification.", inputSchema: interactionSchema("completed") },
  { name: "heartbeat_agent_session", description: "Refresh active source presence and current task claims.", inputSchema: { type: "object", required: ["source_id"], properties: { source_id: { type: "string" }, state: { type: "string" }, current_task_ids: { type: "array", items: { type: "string" } } } } },
  { name: "end_agent_session", description: "Close source presence without deleting its history.", inputSchema: { type: "object", required: ["source_id"], properties: { source_id: { type: "string" } } } },
  { name: "search_work", description: "Search task IDs, titles, and descriptions across authorized projects.", inputSchema: { type: "object", required: ["query"], properties: { project_id: { type: "string" }, query: { type: "string" }, limit: { type: "number" } } } },
  { name: "report_simplify_finding", description: "Corroborate or report a plan-review finding: a duplicate, a task already covered by finished work, work that conflicts with something else in progress, a stale proposal, or something you noticed that doesn't fit those. If another agent or the structural review already flagged the same thing, this adds your agreement to it instead of creating a second entry, and is safe to call more than once: it never double-counts your own agreement. Never proposes an action on its own; a person still decides whether anything changes.", inputSchema: { type: "object", required: ["project_id", "kind", "work_item_id", "reason"], properties: { project_id: { type: "string" }, kind: { type: "string", enum: ["duplicate", "possible_duplicate", "redundant_done", "conflicting_work", "blocked_chain", "started_while_blocked", "stale", "planning_loop", "possibly_implemented", "evidence_removed", "agent_flagged"], description: "Use agent_flagged for anything that doesn't match one of the structural kinds." }, work_item_id: { type: "string" }, related_work_item_id: { type: "string", description: "The other task, for duplicate, possible_duplicate, redundant_done, and conflicting_work." }, reason: { type: "string" }, detail: { type: "string" }, source_id: { type: "string" } } } },
  { name: "get_handoff_package", description: "Get a full project handoff: verified-complete work you must not redo, unverified completion claims worth checking before trusting, currently active work and who holds it, blocked chains, recently rejected approaches, and ranked next actions. Unlike get_planning_context this is not filtered to one objective; call it when picking up a project cold, at the start of a session, or when a person asks you to summarize where things stand.", inputSchema: { type: "object", required: ["project_id"], properties: { project_id: { type: "string" } } } },
  { name: "explain_work_item", description: "Get a causal answer to \"why hasn't this been done\": completed, rejected (with the reason), deferred, blocked by a dependency chain (named down to the root), blocked externally, in progress and by whom, in review awaiting verification, still an unaccepted proposal, or genuinely not started yet. Returns exactly one cause, not a status string.", inputSchema: { type: "object", required: ["work_item_id"], properties: { work_item_id: { type: "string" } } } },
  { name: "get_planning_context", description: "Call this BEFORE planning or proposing new work, not after. Describe what you are about to work on in a sentence; returns what the project already knows that's relevant to it: work already done, in progress and by whom, blocked and why, previously rejected and why, proposals already sitting unimplemented, anyone currently holding a live claim on a file or symbol you're about to touch even if their task's wording looks unrelated, and every open decision in the project (unresolved choices between competing approaches, regardless of whether they mention your objective) plus plain guidance built from those facts. This is how you avoid re-proposing something already finished, already rejected, or already being worked on by someone else. Prefer this over get_project_brief when you are about to create work, since the brief is a status overview and this is filtered to what matters for your specific objective.", inputSchema: { type: "object", required: ["project_id", "objective"], properties: { project_id: { type: "string" }, objective: { type: "string", description: "What you are about to plan or propose, in your own words; a sentence is enough." }, source_id: { type: "string" } } } },
  { name: "record_decision", description: "Raise a decision between two or more competing approaches: this project cannot do both, and someone needs to pick. Either an agent or a person can call this to flag one; it does not settle anything on its own. Link each option to the work item it would keep or create with related_work_item_id where you have one, so resolving the decision can act on it. A person resolves it with resolve_decision.", inputSchema: { type: "object", required: ["project_id", "question", "options", "idempotency_key"], properties: { project_id: { type: "string" }, question: { type: "string", description: "The decision to make, as a short question, for example 'REST or GraphQL for the public API?'" }, description: { type: "string" }, options: { type: "array", minItems: 2, maxItems: 10, items: { type: "object", required: ["label"], properties: { label: { type: "string" }, related_work_item_id: { type: "string", description: "The work item this option keeps or represents, if one already exists. Losing this option later cancels that item as superseded." }, rationale: { type: "string" } } } }, source_id: { type: "string" }, idempotency_key: { type: "string" } } } },
  { name: "resolve_decision", description: "Resolve a decision raised with record_decision, choosing one option. Person only: an agent cannot call this. The losing options are marked rejected, and any work item they were linked to is cancelled as superseded, with a supersedes edge back to this decision, so it surfaces later as a rejected approach rather than a live proposal.", inputSchema: { type: "object", required: ["project_id", "decision_work_item_id", "winning_option_id"], properties: { project_id: { type: "string" }, decision_work_item_id: { type: "string" }, winning_option_id: { type: "string" }, resolution_reason: { type: "string" }, source_id: { type: "string" } } } },
  { name: "submit_reconciliation_judgment", description: "Answer a needsJudgment question from create_work_items: with the repository open, you can usually tell better than a structural score whether two tasks are really the same work. justification is required and must name the specific artifact or behavior that settles it (for example \"different: #31 rotates the signing key, this renews the client's token\"): a bare \"same\" or \"different\" is rejected. This records your answer as evidence; it never merges or links anything on its own.", inputSchema: { type: "object", required: ["project_id", "pair_id", "verdict", "justification"], properties: { project_id: { type: "string" }, pair_id: { type: "string", description: "The pairId from the needsJudgment entry you're answering." }, verdict: { type: "string", enum: ["same", "different"] }, justification: { type: "string", description: "Must name a concrete artifact or behavior, not just restate the verdict." }, source_id: { type: "string" } } } },
  { name: "report_repo_state", description: "Report repository state observed at turn end: the commit sha, branch, file paths changed since the merge base, which of those were deleted or renamed away, and the exit status of a verification command if one ran. Paths and commit metadata only, never file contents or diffs. Work items whose known files intersect the changed paths get evidence attached automatically; evidence is only marked verified when a verification command actually ran and passed. Optionally include symbols (function, class, method, interface, type, or enum names with file and line) parsed from the changed TypeScript/JavaScript files, if you have that available: these ground artifact references in real code instead of a guessed name, and feed the reconciliation engine's precision. Safe to call once per commit even across retries or multiple sessions on one branch.", inputSchema: { type: "object", required: ["project_id", "head_sha"], properties: { project_id: { type: "string" }, source_id: { type: "string" }, head_sha: { type: "string" }, branch: { type: "string" }, changed_paths: { type: "array", maxItems: 200, items: { type: "string" }, description: "Repo-relative file paths only, never contents or diffs." }, deleted_paths: { type: "array", maxItems: 200, items: { type: "string" }, description: "The subset of changed_paths that no longer exists under that name (deleted or renamed away)." }, verification_command: { type: "string", description: "The command that was run, for the record. Not executed by Planbraid." }, verification_exit_code: { type: "number", description: "The exit status of that command. 0 marks matched evidence as verified." }, symbols: { type: "array", maxItems: 2000, items: { type: "object", required: ["name", "kind", "file", "line"], properties: { name: { type: "string" }, kind: { type: "string", enum: ["function", "class", "method", "interface", "type", "enum", "other"] }, file: { type: "string" }, line: { type: "number" } } }, description: "Declaration names found in the changed files, TypeScript/JavaScript only. Names and locations, never source text." } } } },
  { name: "get_planning_health", description: "Get the project's planning debt: every open Simplify finding, weighted by kind and ranked heaviest first, plus a 0-100 score derived from that same list. Always read the debt list, not just the score - the score exists to summarize the list, not to replace it, and a person should act on specific entries, not chase a number. Runs a fresh review pass each call, so this always reflects current state.", inputSchema: { type: "object", required: ["project_id"], properties: { project_id: { type: "string" } } } },
  { name: "get_saved_view", description: "One of five fixed structured views over project state: 'active' (in-progress work and who holds it), 'blocking_release' (which items are blocking the most other work, ranked), 'keeps_getting_proposed' (planning loops - proposed repeatedly with nothing implemented), 'no_proof' (marked done with nothing verifying it), or 'needs_decision' (open decisions awaiting a person). Structured retrieval only, not a natural-language query - pick the view name that matches what you're asking.", inputSchema: { type: "object", required: ["project_id", "view"], properties: { project_id: { type: "string" }, view: { type: "string", enum: [...SAVED_VIEWS] } } } },
];
